import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Header } from '@/app/components/Header/Header';
import styles from '@/app/(home)/page.module.scss';
import { Player } from '@/app/components/Player/Player';
import { Sidebar } from '@/app/components/Sidebar/Sidebar';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { ReactNode } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  const session = await getServerSession(authOptions);
  return (
    <div className={styles.home}>
      <Header></Header>
      {session ? (
        <div className={styles.home_content}>
          <Sidebar></Sidebar>
          {children}
        </div>
      ) : null}

      {session ? <Player></Player> : null}
    </div>
  );
};

export default RootLayout;
